export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';
export const OBTENER_PRODUCTOS_ERROR = 'OBTENER_PRODUCTOS_ERROR';
export const CARGAR_PRODUCTOS = 'CARGAR_PRODUCTOS';
export const ERROR_PRODUCTOS = 'ERROR_PRODUCTOS'; // Asegúrate de añadir esta constante

export const ADD_PRODUCTO = 'ADD_PRODUCTO';
export const EDIT_PRODUCTO = 'EDIT_PRODUCTO';
export const DELETE_PRODUCTO = 'DELETE_PRODUCTO';
