services: 
  webserver:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - user_api
    networks:
      - dev_network

  user_api:
    build:
      context: ./Apis
    deploy: 
      replicas: 10
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    ports:
      - "3000-3010:3000"
    volumes:
      - ./Apis/usuario:/usr/userAPI
    networks:
      - dev_network

  db_dev:
    image: postgres
    container_name: user_db_dev
    deploy:
      resources:
        limits: 
          cpus: "0.2"
          memory: 4GB 
        reservations:
          cpus: "0.1"
          memory: 1GB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./users_data_dev:/var/lib/postgresql/data
    networks:
      - dev_network
  
  pgadmin: 
    image: dpage/pgadmin4
    container_name: dev_pgadmin
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: yeyi@yeyi.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
