FROM postgres:17

# Instalar la extensión pgaudit
RUN apt-get update && \
    apt-get install -y postgresql-contrib && \
    apt-get install -y postgresql-17-pgaudit && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copiar el archivo de configuración al contenedor
COPY postgresql.conf /etc/postgresql/postgresql.conf


# Comando para iniciar PostgreSQL con la configuración personalizada
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]